workflows:
  expo-android-apk:
    name: Expo Native Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 21
    scripts:
      - name: Install Expo Core Dependencies
        script: |
          npm install
      - name: Force Expo Prebuild to Create Native Android Engine
        script: |
          npx expo prebuild --platform android
      - name: Copy Firebase Config to Android
        script: |
          mkdir -p android/app
          cp google-services.json android/app/google-services.json
      - name: Compile and Assemble Heavy Production APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      
